# Jekyll
plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

collections:
  notes:
    output: true
    sort_by: title # Doesn't work?

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      navbar_priority: 999
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: notes
    values:
      layout: note
  - scope:
      path: categories
      type: pages
    values:
      layout: category

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    span:
      disable: true

# jekyll-paginate
paginate: 10
# jekyll-github-metadata
repository: egor-tensin/blog
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@823883ffc36d5b9c02b64a545061c740364e7454

# egor-tensin/jekyll-theme
bootstrap_version: 3.3.7
jquery_version: 1.12.4
html5shiv_version: 3.7.3
respond_version: 1.4.2

excerpt_separator: ""
minified_externals: true

project:
  name: Blog
  description: Egor's blog on programming
baseurl: /blog
personal_info:
  name: Egor Tensin
  email: Egor.Tensin@gmail.com
