# Jekyll
baseurl: /blog

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

collections:
  notes:
    output: true
    # Jekyll 4.0 or later:
    #sort_by: title

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      navbar_priority: 999
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: notes
    values:
      layout: page

excerpt_separator: ''
permalink: none

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    span:
      disable: true

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-remote-theme

# jekyll-github-metadata
repository: egor-tensin/blog
# jekyll-paginate
paginate: 10
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@85e1f6fcdc9ed553fc2a3ac6b9d6d792599138fd

# Theme settings
settings:
  project:
    name: Blog
  author:
    name: Egor Tensin
    email: Egor.Tensin@gmail.com
