plugins:
  - jekyll-paginate
  - jekyll-github-metadata

exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - serve.bat
  - serve.sh
  - README.md

paginate: 10

defaults:
  - scope:
      path: ""
      type: pages
    values:
      navbar_priority: 999

excerpt_separator: ""
include_comments: true
minified_externals: true

highlighter: rouge

markdown: kramdown

kramdown:
  math_engine: null # Ignored by GitHub Pages, yay, how fun!
  syntax_highlighter_opts:
    span:
      disable: true

bootstrap_version: 3.3.7
jquery_version: 1.12.4
html5shiv_version: 3.7.3
respond_version: 1.4.2

project:
  name: Blog
  description: Egor's blog on programming
baseurl: /blog
repository: egor-tensin/blog
personal_info:
  name: Egor Tensin
  email: Egor.Tensin@gmail.com
