name: Jekyll

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 2.7
      JEKYLL_GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}'
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ env.RUBY_VERSION }}'
          bundler-cache: true
      - name: Build
        run: make build
      - name: Check integrity
        run: |
          nohup make serve &
          sleep 5 && make wget
